name: HCF
version: 1.0.0
main: me.kazuto.hcf.Main
description: Hardcore factions
author: KazutoXD
api-version: '1.20.6'
commands:
  test:
  faction:
    aliases: [ f, t, team, squad, F ]
    description: Faction commands.
  balance:
    aliases: [ bal, money, cash, bands, ps ]
  pay:
    usage: "/pay <player> <ammount>"