name: HCF
version: 1.0.0
main: me.kazuto.hcf.Main
description: Hardcore factions
author: KazutoXD
api-version: '1.20.6'
commands:
  faction:
    aliases: [ f, t, team, squad, F ]
    description: Faction commands.